export const RESET_SUCCESS = 'RESET_SUCCESS';
export const RESET_ERROR = 'RESET_ERROR';
export const CHANGE_CURRENT_PAGE = 'CHANGE_CURRENT_PAGE';
export const CHANGE_PAGE_SIZE = 'CHANGE_PAGE_SIZE';
export const BOOK_FIELD_CHANGE = 'BOOK_FIELD_CHANGE';
export const RESET_BOOK = 'RESET_BOOK';

export const FETCH_BOOKS_PAGE_PENDING = 'FETCH_BOOKS_PAGE_PENDING';
export const FETCH_BOOKS_PAGE_FULFILLED = 'FETCH_BOOKS_PAGE_FULFILLED';
export const FETCH_BOOKS_PAGE_REJECTED = 'FETCH_BOOKS_PAGE_REJECTED';

export const CREATE_BOOK_PENDING = 'CREATE_BOOK_PENDING';
export const CREATE_BOOK_FULFILLED = 'CREATE_BOOK_FULFILLED';
export const CREATE_BOOK_REJECTED = 'CREATE_BOOK_REJECTED';

export const FETCH_BOOK_BY_ID_PENDING = 'FETCH_BOOK_BY_ID_PENDING';
export const FETCH_BOOK_BY_ID_FULFILLED = 'FETCH_BOOK_BY_ID_FULFILLED';
export const FETCH_BOOK_BY_ID_REJECTED = 'FETCH_BOOK_BY_ID_REJECTED';

export const UPDATE_BOOK_BY_ID_PENDING = 'UPDATE_BOOK_BY_ID_PENDING';
export const UPDATE_BOOK_BY_ID_FULFILLED = 'UPDATE_BOOK_BY_ID_FULFILLED';
export const UPDATE_BOOK_BY_ID_REJECTED = 'UPDATE_BOOK_BY_ID_REJECTED';

export const DELETE_BOOK_BY_ID_PENDING = 'DELETE_BOOK_BY_ID_PENDING';
export const DELETE_BOOK_BY_ID_FULFILLED = 'DELETE_BOOK_BY_ID_FULFILLED';
export const DELETE_BOOK_BY_ID_REJECTED = 'DELETE_BOOK_BY_ID_REJECTED';
