export const RESET_SUCCESS = 'RESET_SUCCESS';
export const RESET_ERROR = 'RESET_ERROR';
export const CHANGE_CURRENT_PAGE = 'CHANGE_CURRENT_PAGE';
export const CHANGE_PAGE_SIZE = 'CHANGE_PAGE_SIZE';
export const AUTHOR_FIELD_CHANGE = 'AUTHOR_FIELD_CHANGE';
export const RESET_AUTHOR = 'RESET_AUTHOR';

export const FETCH_AUTHORS_PAGE_PENDING = 'FETCH_AUTHORS_PAGE_PENDING';
export const FETCH_AUTHORS_PAGE_FULFILLED = 'FETCH_AUTHORS_PAGE_FULFILLED';
export const FETCH_AUTHORS_PAGE_REJECTED = 'FETCH_AUTHORS_PAGE_REJECTED';

export const CREATE_AUTHOR_PENDING = 'CREATE_AUTHOR_PENDING';
export const CREATE_AUTHOR_FULFILLED = 'CREATE_AUTHOR_FULFILLED';
export const CREATE_AUTHOR_REJECTED = 'CREATE_AUTHOR_REJECTED';

export const FETCH_AUTHOR_BY_ID_PENDING = 'FETCH_AUTHOR_BY_ID_PENDING';
export const FETCH_AUTHOR_BY_ID_FULFILLED = 'FETCH_AUTHOR_BY_ID_FULFILLED';
export const FETCH_AUTHOR_BY_ID_REJECTED = 'FETCH_AUTHOR_BY_ID_REJECTED';

export const UPDATE_AUTHOR_BY_ID_PENDING = 'UPDATE_AUTHOR_BY_ID_PENDING';
export const UPDATE_AUTHOR_BY_ID_FULFILLED = 'UPDATE_AUTHOR_BY_ID_FULFILLED';
export const UPDATE_AUTHOR_BY_ID_REJECTED = 'UPDATE_AUTHOR_BY_ID_REJECTED';

export const DELETE_AUTHOR_BY_ID_PENDING = 'DELETE_AUTHOR_BY_ID_PENDING';
export const DELETE_AUTHOR_BY_ID_FULFILLED = 'DELETE_AUTHOR_BY_ID_FULFILLED';
export const DELETE_AUTHOR_BY_ID_REJECTED = 'DELETE_AUTHOR_BY_ID_REJECTED';
